---
- name: Install contour with Helm.
  community.kubernetes.helm:
    name: contour
    chart_ref: bitnami/contour
    release_namespace: ingress
    create_namespace: true
    values:
      envoy:
        service:
          type: NodePort
          # loadBalancerIP:
          # externalIPs:
