---
- hosts: kube-cluster
  become: yes
  gather_facts: yes
  tasks:
    - name: Install kubeadm
      include_role:
        name: kubeadm
      vars:
        kubernetes_version: 1.18
      when: provider == 'gcp'
  tags:
    - never
    - kubeadm

- hosts: kube-cluster
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize cluster
      include_role:
        name: kube-cluster
      vars:
        kubernetes_version: 1.18
        kubernetes_allow_pods_on_master: true
        kubernetes_apiserver_advertise_address: "{{ kube_master_ip }}"
  tags:
    - never
    - cluster
