---
- name: Install kubeadm packages
  hosts: kube-cluster
  become: yes
  gather_facts: yes
  vars:
    cloud_provider: true
  tasks:
    - name: kubeadm
      include_role:
        name: kubeadm
      vars:
        kubernetes_version: 1.18
      when: cloud_provider | bool
  tags:
    - never
    - kubeadm

- name: Initialize cluster kubernetes
  hosts: kube-cluster
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize
      include_role:
        name: kubernetes
      vars:
        kubernetes_version: 1.18
        kubernetes_allow_pods_on_master: false
        kubernetes_apiserver_advertise_address: "{{ kube_master_ip }}"
  tags:
    - never
    - cluster

- name: Install additional features
  hosts: masters[0]
  become: yes
  gather_facts: yes
  tasks:
    - name: features
      include_role:
        name: kubernetes
      vars:
        kubernetes_features_enabled: true
  tags:
    - never
    - features
