---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    providers:
      - virtualbox

  tasks:
    - name: Build and push the image using Packer.
      command: >
        packer build -var 'version={{ kubernetes_version }}' packer.json
        chdir={{ item }}
      loop: "{{ providers }}"
