---
all:
  vars:
    ansible_ssh_user: fabio
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_python_interpreter: /usr/bin/python3
    cert_manager_acme_email: estudosdevops2019@gmail.com
    nfs_server_address: 10.158.15.222
  children:
    kube-cluster:
      children:
        masters:
          vars:
            kubernetes_role: master
          hosts:
            35.247.213.113:
        nodes:
          vars:
            kubernetes_role: node
          hosts:
            35.199.68.205:
            34.95.201.162:
    front-proxy:
      hosts:
        envoy:
          ansible_host: 34.123.76.144
    nfs-server:
      hosts:
        nfs:
          ansible_host: 35.247.230.56
