---
all:
  vars:
    ansible_ssh_user: fabio
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_python_interpreter: /usr/bin/python3
    cert_manager_acme_email: estudosdevops2019@gmail.com
    cloudflare_api_key: ea33885f9982f34743d9f79d678e50beb2d19
  children:
    kube-cluster:
      children:
        masters:
          vars:
            kubernetes_role: master
          hosts:
            35.199.91.250:
        nodes:
          vars:
            kubernetes_role: node
          hosts:
            35.199.68.205:
            34.95.201.162:
    front-proxy:
      hosts:
        envoy:
          ansible_host: 34.95.164.147
