---
all:
  vars:
    ansible_ssh_user: fabio
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_python_interpreter: /usr/bin/python3
  children:
    kube-cluster:
      children:
        masters:
          vars:
            kubernetes_role: master
          hosts:
            34.95.147.168:
        nodes:
          vars:
            kubernetes_role: node
          hosts:
            34.95.156.77:
            34.95.136.163:
    envoy:
      hosts:
        35.198.16.234:
