---
- name: Create tmp directory
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: Check if Helm is installed
  shell: command -v helm >/dev/null 2>&1
  register: helm_installed
  ignore_errors: yes

- name: Install helm
  block:
    - name: Get helm installer v3
      get_url:
        url: "{{ kubernetes_helm_installer_file }}"
        dest: "{{ tmp_dir }}"
        mode: 0755

    - name: Run the installer
      shell: "{{ tmp_dir }}/get-helm-{{ kubernetes_helm_version }}"
  when: helm_installed.rc > 0

- name: Add helm chart's repository.
  community.kubernetes.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.repo_url }}"
  loop:
    - { name: "bitnami", repo_url: "{{ kubernetes_helm_chart_bitnami_url }}" }
    - { name: "stable", repo_url: "{{ kubernetes_helm_chart_stable_url }}" }
    - { name: "jetstack", repo_url: "{{ kubernetes_cert_manager_chart_url }}" }
    - { name: "appscode", repo_url: "{{ kubernetes_appscode_chart_url }}" }
    - { name: "drone", repo_url: "{{ kubernetes_drone_chart_url }}" }
    - { name: "center", repo_url: "{{ kubernetes_chartcenter_url }}" }
