---
galaxy_info:
  author: Fabio Coelho
  description: Install kubernetes packages for linux
  company: GPiT Consultoria

  license: license (BSD, MIT)

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - system
    - docker
    - kubadmin
    - k8s

dependencies: []
