---
- name: Copy template apps hello-k8s
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  loop:
    - { src: app-example-hello.yaml.j2, dest: "{{ tmp_dir }}/app-example-hello.yaml" }

- name: Configure a basic issuers stg, prd
  command: "{{ item }}"
  loop:
    - kubectl apply -f {{ tmp_dir }}/app-example-hello.yaml
  register: apps_result
  changed_when: "'created' in apps_result"
